"""
Django settings for si2Backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_%5gwe5wnt1+iizs9n)5ne(ydoja9t7#&#1clz2j4!55p#j(os'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Permitir todos los hosts (proyecto académico)
ALLOWED_HOSTS = ['*']

# CSRF - Permitir todos los orígenes (proyecto académico)
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'http://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    
]

# Añadir orígenes extra para desarrollo (p. ej. Vite/CRA en puerto 5173)
# Se puede extender mediante la variable de entorno CSRF_TRUSTED_ORIGINS_EXTRA
EXTRA_CSRF_TRUSTED = env.list('CSRF_TRUSTED_ORIGINS_EXTRA', default=[
    'http://localhost:5173',
    'http://127.0.0.1:5173',
])

for origin in EXTRA_CSRF_TRUSTED:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# decidir si activamos CORS desde .env
USE_CORS = env.bool('USE_CORS', default=True)

# CORS settings (development-friendly). Ajusta/limita en producción.
if USE_CORS:
    # Permitir todos los orígenes para desarrollo local (cambia a CORS_ALLOWED_ORIGINS en producción)
    CORS_ALLOW_ALL_ORIGINS = True
    # Permitir envío de credenciales (cookies) si el front los usa
    CORS_ALLOW_CREDENTIALS = True
    # Headers/methods defaults (asegura que Authorization y Content-Type estén permitidos)
    try:
        from corsheaders.defaults import default_headers, default_methods
        CORS_ALLOW_HEADERS = list(default_headers) + [
            'authorization',
            'content-type',
        ]
        CORS_ALLOW_METHODS = list(default_methods)
    except Exception:
        # corsheaders not installed or defaults not available yet; middleware will raise if missing
        CORS_ALLOW_HEADERS = ['authorization', 'content-type']
        CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

    # Expose common headers (e.g. for file downloads)
    CORS_EXPOSE_HEADERS = [
        'Content-Disposition',
        'Authorization',
    ]

    # Limit CORS handling to API routes by default (optional)
    CORS_URLS_REGEX = r'^/api/.*$'

    # If you need credentialed requests from the frontend (fetch with credentials: 'include'),
    # do NOT leave CORS_ALLOW_ALL_ORIGINS = True — instead configure the explicit origins
    # via the CORS_ALLOWED_ORIGINS env var. Example in .env: CORS_ALLOWED_ORIGINS=http://localhost:3000
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
    if CORS_ALLOWED_ORIGINS:
        # when specific origins are set, disable the wildcard
        CORS_ALLOW_ALL_ORIGINS = False
        CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'cloudinary',
    'cloudinary_storage',
    'corsheaders',  # <- SOLO AQUI, una sola vez
    'usuarios',
    'productos',  # nueva app
    'categorias',  # app de categorías añadida
    'reportes',
    'ventas',
]

# ya se añadieron arriba 'cloudinary' y 'cloudinary_storage' — no repetirlos

if USE_CORS:
    # NO añadir corsheaders aquí de nuevo — ya está arriba
    pass

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # debe ir primero
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'si2Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'si2Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ecomerce_db',
        'USER': 'postgres',
        'PASSWORD': '7722794',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Cloudinary Configuration
#CLOUDINARY_STORAGE = {
 #   'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
  #  'API_KEY': env('CLOUDINARY_API_KEY'),
   # 'API_SECRET': env('CLOUDINARY_API_SECRET'),
#}

# Set Cloudinary as default file storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Media files (local fallback)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "usuarios.authentication.CustomJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # Duración del token de acceso
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Duración del token de refresco
    'ROTATE_REFRESH_TOKENS': True,                    # Genera nuevo refresh token al refrescar
    'BLACKLIST_AFTER_ROTATION': True,                 # Invalida el refresh token anterior
    'UPDATE_LAST_LOGIN': False,                       # Deshabilitado porque Usuario no tiene last_login
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'idUsuario',  # Campo ID personalizado
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}
