# Generated by Django 5.2.7 on 2025-11-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UserNoti',
            fields=[
                ('idUserNoti', models.AutoField(primary_key=True, serialize=False)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_notificacion', to='notificaciones.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_usuario', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Notificación',
                'verbose_name_plural': 'Usuarios Notificaciones',
                'db_table': 'user_noti',
                'ordering': ['-notificacion__fecha_creacion'],
            },
        ),
    ]
