# Generated by Django 5.2.8 on 2025-11-11 17:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_comprobante', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('datos_cliente', models.JSONField(help_text='Nombre, email, teléfono, dirección al momento del pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20)),
                ('comprobante_pago', models.CharField(blank=True, max_length=255)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Pedido expira si no se paga (ej: 30 minutos)', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.usuario')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ventas.metodopago')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(default='', max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stock_reservado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedido')),
                ('producto', models.ForeignKey(help_text='Producto base', on_delete=django.db.models.deletion.PROTECT, to='productos.product')),
                ('variante', models.ForeignKey(blank=True, help_text='Variante específica (talla/color)', null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.productvariant')),
            ],
            options={
                'db_table': 'pedido_item',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datos_cliente', models.JSONField(default=dict)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de costos de todos los productos (snapshot)', max_digits=12)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='total - costo_total', max_digits=12)),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(ganancia / costo) * 100', max_digits=5)),
                ('comprobante_pago', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='usuarios.usuario')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.metodopago')),
                ('pedido', models.OneToOneField(blank=True, help_text='Pedido origen de esta venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='ventas.pedido')),
                ('usuario_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_procesadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('RESERVA', 'Reserva (pedido creado)'), ('VENTA', 'Venta (pedido confirmado)'), ('CANCELACION', 'Cancelación (liberar stock)'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste manual')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.productvariant')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pedido')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(default='', max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('categoria_nombre', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de VENTA unitario', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='cantidad * precio_unitario', max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de COSTO unitario (snapshot)', max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='cantidad * costo_unitario', max_digits=12)),
                ('ganancia_unitaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='precio_unitario - costo_unitario', max_digits=12)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal - costo_total', max_digits=12)),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(ganancia_unitaria / costo_unitario) * 100', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.product')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.productvariant')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='pedido_estado_f67d23_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'fecha_creacion'], name='pedido_cliente_287bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha', 'estado'], name='venta_fecha_c47298_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario_vendedor', 'fecha'], name='venta_usuario_ca3a52_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente', 'fecha'], name='venta_cliente_618fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['variante', 'fecha'], name='movimiento__variant_506974_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo', 'fecha'], name='movimiento__tipo_61cc46_idx'),
        ),
    ]
