# Generated by Django 5.2.7 on 2025-11-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_product_categoria'),
        ('usuarios', '0002_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.productvariant')),
            ],
            options={
                'db_table': 'inventory_movement',
                'ordering': ['-fecha'],
            },
        ),
    ]
