# Generated by Django 5.2.8 on 2025-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de adquisición. Si está vacío, usa el costo del producto.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta al público. Si está vacío, usa el precio del producto.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'size', 'color'], name='product_var_product_75ab83_idx'),
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variant',
        ),
    ]
